from aiogram.dispatcher.filters.state import StatesGroup, State

class Form(StatesGroup):
    GetPhone = State()
    GetInfo = State()
    GetUsername = State()
    AddUsername = State()
    AddUsernameLike = State()
    GiveLike = State()
    CheckLike = State()
    GiveComment = State()
    CheckComment = State()
    RecieveComment = State()
    RecieveLike = State()
    GetCommentLink = State()
    GetLikeLink = State()
    GetCommentText = State()
    SetCommentText = State()
    SetLikeText = State()
    SendComment = State()